CREATE TABLE prices (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(10) NOT NULL UNIQUE,
    price DECIMAL(18, 8) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO prices (symbol, price) VALUES ('BTCUSD', 60000.00) ON CONFLICT (symbol) DO NOTHING;